phone: "+084 822 2208 98"
mail: "Bhhoang1998@gmail.com"
skype: "shinigami_220898"
location: "https://inuvcuon.vn/images/2018/08/voi-nhung-cong-cu-rat-huu-ich-ban-da-co-the-in-truc-tiep-ngay-tren-google-map.jpg"
img_little_about_us: "https://live.staticflickr.com/2474/3884195824_0fcd9fc1c7_b.jpg"
img_list_room_item: "https://images.adsttc.com/media/images/5bbf/eabb/f197/ccec/bc00/03fd/slideshow/800_6652_post_HR.jpg?1539304112"
client: 320
staff: 50
room: 24
award: 12
deposit: 10
home:
  path_link1: "logo-monalisa-healing-gold.png"
profile:
    image_ava: "avatar.jpg"
user:
  validate:
    name_max: 50
    email_max: 255
    pass_min: 6
  page: 5
  cancel: 3
  accept: 1
  complete: 2
room_view:
  validate:
    name_max: 50
users:
  edit:
    type: "image/jpeg, image/gif, image/png"
type:
  validate:
    name_max: 50
unity:
  validate:
    name_max: 50
service:
  validate:
    name_max: 50
    des_max: 1000
rooms:
  rooms_to_show: 4
  relate_rooms: 3
  room_per_page: 5
  validate:
    name_max: 100
    des: 1000
reservation:
  page: 3
bill:
  page: 5
  mini: 86400
  day: 1
bills_per_page: 5
booking_per_page: 10
users_per_page: 15
comments:
  comment_content: 200
